### ISSUE TITLE
Error when running web.py file

### ISSUE THREAD

**Issue by tshan1229** [Arri/Py_WebSurveillance#1]
127.0.0.1 - - [18/Jun/2018 18:50:39] "GET / HTTP/1.1" 200 -
Camera warming up ...
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/shan/.virtualenvs/dl4cv/lib/python3.5/site-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/home/shan/.virtualenvs/dl4cv/lib/python3.5/site-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "/home/shan/Downloads/Py_WebSurveillance-master/web.py", line 23, in gen
    frame = camera.get_frame()
  File "/home/shan/Downloads/Py_WebSurveillance-master/camera.py", line 43, in get_frame
    return self.frames.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
127.0.0.1 - - [18/Jun/2018 18:50:42] "GET /video_feed HTTP/1.1" 200 -

**Comment by muyurainy** [comment]
This is a python code problem. When I use python3, I also meet this problem, but python2 is ok.
